### ISSUE TITLE
ruby 1.9 support

### ISSUE THREAD

**Issue by tbarbugli** [99designs/http-signatures-ruby#3]
seems like its not supported, if not super hard I am willing to contribute. do you have any input about this?

**Comment by pda** [comment]
I don't personally have any interest in Ruby 1.9. It's currently in security maintenance mode, and all support is due to be dropped next month:

> After February 23 2014, we will only provide security fixes for 1.9.3 until February 23 2015, after which all support will end for 1.9.3.
— https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

Once security fixes are discontinued, I think it's actually dangerous to encourage its continued use by backporting new libraries like this one.

From a technical point of view, I've taken considerable advantage of keyword-arguments introduced in Ruby 2.0, so I think changes to support Ruby 1.9 would weaken the library.

I certainly appreciate the offer to help, but I'd rather not go ahead with this. Thanks anyway!
