### ISSUE TITLE
Rubygems.org Availability?

### ISSUE THREAD

**Issue by waynerobinson** [99designs/http-signatures-ruby#7]
Is this gem available on rubygems.org at all? I'd like to use it as a dependency in one of my client gems.

**Comment by pda** [comment]
I couldn't find it either, was very puzzled. Went to `gem push` it, RubyGems responded it already exists. Turns out it's at https://rubygems.org/gems/http_signatures (underscored name as per convention) and [searching with a hyphen](https://rubygems.org/search?query=http-signatures) can't find it. Maybe the hyphenated name can be added to some search-indexed metadata…
